ysmoOCTSIM/usb/class/dfu: fix missing include
Fix for:

../usb/class/dfu/device/dfudf.c:199:17: error: implicit declaration of function 'delay_us' [-Wimplicit-function-declaration]

Change-Id: Ia36d25d47f4d5dc4e38c1ea9c8e193ff52f5b5d1