ccid_gen_notify_slot_status: add msgb_put cast
Fix this error seen in master-osmo-ccid-firmware after switching to
debian trixie with 14.2:

../main.c:338:57: error: initialization of 'struct ccid_rdr_to_pc_notify_slot_change *' from incompatible pointer type 'unsigned char *' [-Wincompatible-pointer-types]
  338 |         struct ccid_rdr_to_pc_notify_slot_change *nsc = msgb_put(msg, sizeof(*nsc) + sizeof(statusbytes));

Change-Id: I5618297533246adc8adaacf49fd58ec1f0f97cfc