ccid_hosts: fix missing talloc_report_full
Fix for:

ccid_main_functionfs.c:534:17: error: implicit declaration of function 'talloc_report_full' [-Wimplicit-function-declaration]
  534 |                 talloc_report_full(g_tall_ctx, stderr);

Change-Id: I2b79d6f28e80acef8e1cab0dab949233698336ad