contrib/jenkins: use osmo-clean-workspace.sh
Clean the workspace at the beginning, because otherwise the build fails
when running twice in a row. For some reason a pseudo-talloc.h from
libosmocore appears, resulting in:

  error: implicit declaration of function 'talloc_report_full'

Change-Id: If2e29ffd5150b57858b46e92e157f83a0cf3a11a